MONGO:
  HOST: 127.0.0.1
  PORT: 27017
  AUTHENTICATION:
    ENABLED: true
    USERNAME: admin
    DATABASE: admin
    PASSWORD:
CHAT-FORMAT: "{PLAYERNAME} {MESSAGE}"
# PlayerName and Message must ALWAYS be included!
# Message must always be after playername.
